<?php

namespace App\HHH_Library\ThisApp\API\Betconstruct\ExternalAdmin\Helpers\Tests\Enums;

enum TestResponseEnum: string
{
        // Success responses
    case GetClients_Success = '{"StatusCode":"0","Data":[{"Id":1417505119,"CurrencyId":"TOM","IBAN":null,"Name":"بابائی ولوجائی علی","FirstName":"علی","LastName":"بابائی ولوجائی","MiddleName":null,"Login":"alibabaei3779","RegionCode":"IR","Gender":null,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":null,"Email":null,"Language":"fa","Phone":"9809016504829","MobilePhone":null,"BirthDateStamp":null,"City":null,"PromoCode":null,"BTag":null,"ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1685025897,"ModifiedStamp":1685025897,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":0.00,"LastLoginIp":"2.147.140.106","LastLoginTimeStamp":1685025899,"PreMatchSelectionLimit":100.00,"LiveSelectionLimit":100.00,"IsVerified":false,"SportsbookProfileId":1,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":0.00,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":null,"CustomPlayerCategory":null,"RequestHash":null},{"Id":1417505041,"CurrencyId":"IRT","IBAN":null,"Name":"goles ali","FirstName":"ali","LastName":"goles","MiddleName":null,"Login":"aligoles2233","RegionCode":null,"Gender":null,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":null,"Email":null,"Language":"fa","Phone":"989129495535","MobilePhone":null,"BirthDateStamp":null,"City":null,"PromoCode":null,"BTag":null,"ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1685025895,"ModifiedStamp":1685025895,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":0.00,"LastLoginIp":"89.38.99.75","LastLoginTimeStamp":1685025897,"PreMatchSelectionLimit":100.00,"LiveSelectionLimit":100.00,"IsVerified":false,"SportsbookProfileId":1,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":0.00,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":null,"CustomPlayerCategory":null,"RequestHash":null}]}';
    case GetClient_Success = '{"StatusCode":"0","Data":[{"Id":222164184,"CurrencyId":"TOM","IBAN":null,"Name":"toman ferhad","FirstName":"ferhad","LastName":"toman","MiddleName":null,"Login":"ferhadtom","RegionCode":"ZW","Gender":null,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":null,"Email":"ferhadtom@betcartemail.com","Language":"ar","Phone":"00989911200505","MobilePhone":null,"BirthDateStamp":446515200,"City":null,"PromoCode":null,"BTag":null,"ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1588659974,"ModifiedStamp":1684862488,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":212600.12,"LastLoginIp":"91.72.74.74","LastLoginTimeStamp":1684998141,"PreMatchSelectionLimit":100.00,"LiveSelectionLimit":100.00,"IsVerified":false,"SportsbookProfileId":6,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":155800.12,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":false,"CustomPlayerCategory":null,"RequestHash":null}]}';
    case CreateClient_Success = '{"StatusCode":"0","Data":{"MaxDailyDeposit":null,"MaxWeeklyDeposit":null,"MaxMonthlyDeposit":null,"MaxYearlyDeposit":null,"MaxSingleDeposit":null,"Id":2135868012,"CurrencyId":"IRT","IBAN":null,"Name":"نام خانوادگی تست","FirstName":"تست","LastName":"نام خانوادگی","MiddleName":null,"BirthName":null,"Login":"testUser3","RegionCode":null,"Gender":1,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":null,"Email":null,"Language":"fa","Phone":null,"MobilePhone":null,"BirthDateStamp":1679400000,"City":null,"PromoCode":null,"BTag":null,"ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1702972573,"ModifiedStamp":1702972573,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":0.0,"LastLoginIp":null,"LastLoginTimeStamp":null,"PreMatchSelectionLimit":100.0,"LiveSelectionLimit":100.0,"IsVerified":false,"SportsbookProfileId":1,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":0.0,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":null,"CustomPlayerCategory":null,"RequestHash":null}}';
    case UpdateClient_Success = '{"StatusCode":"0","Data":{"Id":222164184,"CurrencyId":"TOM","IBAN":null,"Name":"بهرامی آرمان","FirstName":"آرمان","LastName":"بهرامی","MiddleName":null,"BirthName":null,"Login":"ferhadtom","RegionCode":"ZW","Gender":1,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":null,"Email":"ferhadtom@betcartemail.com","Language":"ar","Phone":"00989911200505","MobilePhone":null,"BirthDateStamp":446515200,"City":null,"PromoCode":null,"BTag":null,"ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1588659974,"ModifiedStamp":1699459877,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":212600.12,"LastLoginIp":"91.74.6.66","LastLoginTimeStamp":1699450415,"PreMatchSelectionLimit":100.00,"LiveSelectionLimit":100.00,"IsVerified":false,"SportsbookProfileId":6,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":155800.12,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":false,"CustomPlayerCategory":null,"RequestHash":null}}';
    case ChangeClientPassword_Success = '{"StatusCode":"0","Data":{"Id":222164184,"CurrencyId":"TOM","IBAN":null,"Name":"بهرامی آرمان","FirstName":"آرمان","LastName":"بهرامی","MiddleName":null,"BirthName":null,"Login":"ferhadtom","RegionCode":"Ir","Gender":1,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":null,"Email":"ferhadtom@betcartemail.com","Language":"ar","Phone":"00989911200505","MobilePhone":null,"BirthDateStamp":446515200,"City":null,"PromoCode":null,"BTag":null,"ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1588659974,"ModifiedStamp":1699459877,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":212600.12,"LastLoginIp":"91.74.6.66","LastLoginTimeStamp":1699450415,"PreMatchSelectionLimit":100.00,"LiveSelectionLimit":100.00,"IsVerified":false,"SportsbookProfileId":6,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":155800.12,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":false,"CustomPlayerCategory":null,"RequestHash":null}}';
    case GetBets_Success = '{"StatusCode":"0","Data":[{"AuthToken":null,"TransactionId":147906587545,"BetId":3778725021,"HashCode":"1695133","Amount":5.00,"Created":"2024-01-17T14:08:44.521Z","CalcDate":null,"BetType":1,"SystemMinCount":null,"SelectionCount":1,"TotalPrice":1.220,"BonusBetAmount":null,"BonusId":null,"Source":42,"State":1,"CashoutAmount":null,"AcceptTypeId":0,"OddType":0,"Selections":[{"SelectionId":4296219950,"SelectionName":"W2","MarketTypeId":5498,"MarketName":"Match Result","MatchId":23729087,"MatchShortId":122219,"MatchName":"Iraq - Japan","MatchStartDate":"2024-01-19T11:30:00Z","RegionId":3,"RegionName":"Asia","CompetitionId":1691,"CompetitionName":"AFC Asian Cup","SportId":1,"SportName":"Football","SportAlias":"Soccer","Price":1.220,"IsLive":false,"Basis":0.00,"MatchInfo":null,"IsOutright":false,"State":0,"SelectionScore":"","ReSettlementReason":null,"RequestHash":null}],"IsLive":false,"WinAmount":0.00,"Currency":"IRT","PaymentDate":null,"BetShop":null,"CashDesk":null,"CashDeskId":null,"InfoCashDeskId":null,"ClientId":101452623,"Number":null,"ExternalId":null,"PaymentBetShop":null,"BarCode":37787250212,"BetShopGroupName":"","PossibleTaxAmount":0.00,"ParentBetId":null,"PossibleWin":6.10,"AcceptLowerOdds":false,"IsEachWay":null,"HashToCheck":null,"RequestHash":null},{"AuthToken":null,"TransactionId":147906545791,"BetId":3778723209,"HashCode":"2055666","Amount":5.00,"Created":"2024-01-17T14:08:09.235Z","CalcDate":null,"BetType":1,"SystemMinCount":null,"SelectionCount":1,"TotalPrice":1.790,"BonusBetAmount":null,"BonusId":null,"Source":42,"State":1,"CashoutAmount":null,"AcceptTypeId":0,"OddType":0,"Selections":[{"SelectionId":4310781227,"SelectionName":"W1","MarketTypeId":5498,"MarketName":"Match Result","MatchId":23796440,"MatchShortId":104021,"MatchName":"Royale Union Saint-Gilloise - RSC Anderlecht","MatchStartDate":"2024-01-17T19:30:00Z","RegionId":29,"RegionName":"Belgium","CompetitionId":1788,"CompetitionName":"Belgian Cup","SportId":1,"SportName":"Football","SportAlias":"Soccer","Price":1.790,"IsLive":false,"Basis":0.00,"MatchInfo":null,"IsOutright":false,"State":0,"SelectionScore":"","ReSettlementReason":null,"RequestHash":null}],"IsLive":false,"WinAmount":0.00,"Currency":"IRT","PaymentDate":null,"BetShop":null,"CashDesk":null,"CashDeskId":null,"InfoCashDeskId":null,"ClientId":101452623,"Number":null,"ExternalId":null,"PaymentBetShop":null,"BarCode":37787232096,"BetShopGroupName":"","PossibleTaxAmount":0.00,"ParentBetId":null,"PossibleWin":8.95,"AcceptLowerOdds":false,"IsEachWay":null,"HashToCheck":null,"RequestHash":null}]}';
    case GetPartnerBonuses_Success = '{"StatusCode":"0","Data":[{"Id":76722,"Name":"Exact Losing Express 4- 10%","Description":"Bonus on Exact Losing","InternalDesc":null,"StartDateTS":-62135596800,"EndDateTS":null,"ExpirationDays":null,"Type":1,"Triggertype":0,"ExternalId":null,"IsDisabled":false,"PlayerMaxCount":null,"Note":null,"RequestHash":null},{"Id":76723,"Name":"Exact Losing Express 5- 20%","Description":"Bonus on Exact Losing","InternalDesc":null,"StartDateTS":-62135596800,"EndDateTS":null,"ExpirationDays":null,"Type":1,"Triggertype":0,"ExternalId":null,"IsDisabled":false,"PlayerMaxCount":null,"Note":null,"RequestHash":null}]}';
    case clientBalanceCorrection_Success = '{"StatusCode":"0","Data":{"ClientId":101452623,"CurrencyId":"IRT","PaymentSystemId":null,"Amount":10.01,"Info":"test","DocumentType":301,"DocumentId":151323534990,"ExternalId":null,"RequestHash":null}}';
    case AddClientToBonus_Success = '{"StatusCode":"0","Data":{"Id":628754328,"ClientId":101452623,"PartnerBonusId":171911,"Name":"⚽ کاربر برنز: شرط رایگان قدردانی‌","Description":"توضیحات: ۱- برای استفاده، شرط مورد نظر خود را انتخاب کنید. از داخل برگه شرط بندی کنار ستاره بنفش شرط رایگان را روشن کنید. اگر چند شرط رایگان داشته باشید، میتوانید یکی‌ را انتخاب کنید. ۲- در صورت برد، تنها مبلغ برد به حساب شما اضافه میشود. ۳- در صورت برگشت یا لغو شرط، شرط رایگان حذف میشود. ۴- با شرط رایگان می‌توان هر مبلغی برنده شد. ۵- شرط رایگان قابل استفاده در تمامی‌ ورزش‌ها و انواع شرط میباشد.","Amount":10.01,"CreatedStamp":1709014186,"ExpirationDateStamp":1709446186,"RequestHash":null}}';

    /** Succes responses with issue **/
        // Date issue
    case GetClient_Success_2 = '{"StatusCode":"0","Data":[{"Id":270834480,"CurrencyId":"TOM","IBAN":null,"Name":"میربلوچ عبدالواحد","FirstName":"عبدالواحد","LastName":"میربلوچ","MiddleName":null,"Login":"vahed1399v","RegionCode":"IR","Gender":null,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":null,"Email":"vahed1399v@betcartemail.com","Language":"fa","Phone":"00989020024997","MobilePhone":null,"BirthDateStamp":586915200,"City":null,"PromoCode":null,"BTag":"217058_l109353","ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1601575313,"ModifiedStamp":1652504604,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":546.11,"LastLoginIp":"185.85.241.68","LastLoginTimeStamp":1688358010,"PreMatchSelectionLimit":100.00,"LiveSelectionLimit":100.00,"IsVerified":false,"SportsbookProfileId":2,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":0.00,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":null,"CustomPlayerCategory":null,"RequestHash":null}]}';
        // Long city issue
    case GetClient_Success_3 = '{"StatusCode":"0","Data":[{"Id":93272308,"CurrencyId":"IRT","IBAN":null,"Name":"گلستانی حتکنی محمد","FirstName":"محمد","LastName":"گلستانی حتکنی","MiddleName":null,"Login":"m.golestani25001","RegionCode":"IR","Gender":1,"ProfileId":null,"DocNumber":null,"PersonalId":null,"Address":"استان کرمان شهرستان زرندشهرک امام.خیابان هدایت6منزل7","Email":"m.golestani25001@betcartemail.com","Language":"fa","Phone":"989137202614","MobilePhone":null,"BirthDateStamp":665107200,"City":"استان کرمان شهرستان زرند.شهرک امام.خیابان هدایت6منزل7","PromoCode":null,"BTag":null,"ExtAgentId":null,"TimeZone":null,"IsLocked":false,"IsSubscribedToNewsletter":false,"CreatedStamp":1547231347,"ModifiedStamp":1691017856,"ExcludedStamp":null,"RFId":null,"NickName":null,"ResetCode":null,"ResetExpireDateStamp":null,"DocIssuedBy":null,"Balance":0.24,"LastLoginIp":"98.98.215.120","LastLoginTimeStamp":1691819075,"PreMatchSelectionLimit":100.00,"LiveSelectionLimit":100.00,"IsVerified":false,"SportsbookProfileId":2,"GlobalLiveDelay":null,"ExcludedLastStamp":null,"UnplayedBalance":0.20,"IsTest":false,"Password":null,"ExternalId":null,"ZipCode":null,"TermsAndConditionsVersion":null,"CanDeposit":null,"CanWithdraw":null,"CanLogin":null,"CanBet":null,"IsExcludedFromBonuses":false,"CustomPlayerCategory":315,"RequestHash":null}]}';

        // Duplicate IBAN
    case UpdateClient_Failed_DuplicateIBAN = '{"StatusCode":"DuplicateIBAN","Data":"Duplicate IBAN"}';

    case AddClientToBonus_Failed_InvalidClientBonus = '{"StatusCode":"InvalidClientBonus","Data":"Invalid Client Bonus"}';

    case AddClientToBonus_Failed_PartnerBonusNotFound = '{"StatusCode":"PartnerBonusNotFound","Data":"Partner Bonus Not Found"}';
}
