<?php

namespace App\HHH_Library\ThisApp\API\Betconstruct\SwarmApi\Helpers\Tests\Enums;

enum TestResponseEnum: string
{
        // Success responses
    case RequestSession_Success = '{"code":0,"data":{"ctx":{"k_type":"None","site":934,"tree_mode":"dict"},"host":"europe-west4-a-c7-swarm-test-cd15","ip":"91.72.74.74, 162.158.56.151, 34.120.174.72","recaptcha_actions":["login","register","apply_promo_codes","do_bet","get_max_bet","apply_scratch_card"],"recaptcha_enabled":true,"recaptcha_version":3,"sid":"6f429da1-3df5-414e-71ca-c4847c9d6119-1","site_key":"6LeR4MAUAAAAAEsIF4FFxLHl20dZpu_8_K9osriA","version":"1.0.82"}}';
    case Login_Success = '{"code":0,"data":{"auth_token":"3FEE3C66D9C9E0B796273CF91803486A","authentication_status":0,"deposit_count":8,"is_new_client":null,"qr_code_origin":null,"user_id":222164184}}';
    case GetUser_Success = '{"code":0,"data":{"auth_token":"6FFD538449DCF6CBC0D29A0B68F1B849","authentication_status":0,"balance":212600.12,"birth_date":"1984-02-25","bonus_balance":0.0,"bonus_money":0.0,"bonus_win_balance":0.0,"casino_balance":null,"casino_bonus":0.0,"casino_bonus_win":0.0,"casino_unplayed_balance":null,"client_notifications":null,"counter_offer_min_amount":5000000.0,"country_code":"ZW","currency":"TOM","currency_name":"TOM","deposit_count":8,"doc_region_id":0,"email":"ferhadtom@betcartemail.com","first_name":"ferhad","frozen_balance":0.0,"has_free_bets":false,"incorrect_fields":null,"is_agent":false,"is_bonus_allowed":true,"is_cash_out_available":true,"is_gdpr_passed":true,"is_mobile_phone_verified":false,"is_phone_verified":false,"is_super_bet_available":true,"is_tax_applicable":false,"is_two_factor_authentication_enabled":null,"is_verified":false,"language":"ar","last_login_date":1687511450,"last_login_ip":"185.85.241.71","last_name":"toman","loyalty_earned_points":0.0,"loyalty_exchanged_points":0.0,"loyalty_last_earned_points":0.0,"loyalty_level_id":362,"loyalty_max_exchange_point":0,"loyalty_min_exchange_point":0,"loyalty_point":0.0,"loyalty_point_usage_period":0,"name":"ferhad ","personal_id":null,"phone":"00989911200505","reg_date":"2020-05-05","site_id":934,"sport_bonus":0.0,"sportsbook_profile_id":6,"status":1,"subscribe_to_bonus":true,"subscribe_to_email":true,"subscribe_to_internal_message":true,"subscribe_to_phone_call":true,"subscribe_to_push_notification":true,"subscribe_to_sms":true,"subscribed_to_news":false,"terms_and_conditions_acceptance_date":null,"terms_and_conditions_version":null,"unique_id":222164184,"unplayed_balance":155800.12,"unread_count":0,"user_id":222164184,"username":"ferhadtom","zip_code":null}}';
    case GetUser_Success_2 = '{"code":0,"data":{"address":"تهران تهرانپارس خیابان جشنواره خیابان زارع بن بست اول","auth_token":"2D19E68E69D1D688B133ADF58B784C2D","authentication_status":0,"balance":12006.14,"birth_date":"1966-03-26","bonus_balance":0.0,"bonus_money":0.0,"bonus_win_balance":0.0,"btag":"378143","casino_balance":null,"casino_bonus":0.0,"casino_bonus_win":0.0,"casino_unplayed_balance":null,"city":"تهران","client_notifications":null,"counter_offer_min_amount":5000000.0,"country_code":"IR","currency":"TOM","currency_name":"TOM","deposit_count":748,"doc_region_id":0,"email":"Adhamm@betcartemail.com","first_name":"بهجت","frozen_balance":0.0,"gender":"F","has_free_bets":false,"incorrect_fields":null,"is_agent":false,"is_bonus_allowed":true,"is_cash_out_available":true,"is_gdpr_passed":true,"is_mobile_phone_verified":false,"is_phone_verified":false,"is_super_bet_available":true,"is_tax_applicable":false,"is_two_factor_authentication_enabled":null,"is_verified":false,"language":"fa","last_login_date":1688545845,"last_login_ip":"185.85.241.68","last_name":"ادهم","loyalty_earned_points":0.0,"loyalty_exchanged_points":0.0,"loyalty_last_earned_points":0.0,"loyalty_level_id":362,"loyalty_max_exchange_point":0,"loyalty_min_exchange_point":0,"loyalty_point":2.0,"loyalty_point_usage_period":0,"name":"بهجت ","owner_id":null,"personal_id":null,"phone":"00989353128538","reg_date":"2021-01-15","site_id":934,"sport_bonus":0.0,"sportsbook_profile_id":6,"status":1,"subscribe_to_bonus":true,"subscribe_to_email":true,"subscribe_to_internal_message":true,"subscribe_to_phone_call":true,"subscribe_to_push_notification":true,"subscribe_to_sms":true,"subscribed_to_news":false,"terms_and_conditions_acceptance_date":null,"terms_and_conditions_version":null,"unique_id":318415244,"unplayed_balance":10160.0,"unread_count":0,"user_id":318415244,"username":"Adhamm","zip_code":null}}'; // issue: saving birth_date
    case GetUser_Success_3 = '{"code":0,"data":{"auth_token":"C7D92689774C50CA24D898B4D909DFFD","authentication_status":0,"balance":0.71,"birth_date":"1986-09-21","bonus_balance":10000.0,"bonus_money":0.0,"bonus_win_balance":0.0,"casino_balance":null,"casino_bonus":0.0,"casino_bonus_win":0.0,"casino_unplayed_balance":null,"city":"رشت","client_notifications":null,"counter_offer_min_amount":5000.0,"country_code":"IR","currency":"IRT","currency_name":"IRT","deposit_count":1069,"doc_region_id":0,"email":"vahidmahboob60@betcartemail.com","external_id":"177663","first_name":"Vahid Mahboob","frozen_balance":0.0,"gender":"M","has_free_bets":false,"iban":"260140040000310048382785","incorrect_fields":null,"is_agent":false,"is_bonus_allowed":true,"is_cash_out_available":true,"is_gdpr_passed":true,"is_mobile_phone_verified":false,"is_phone_verified":false,"is_super_bet_available":true,"is_tax_applicable":false,"is_two_factor_authentication_enabled":null,"is_verified":false,"language":"fa","last_login_date":1688545676,"last_login_ip":"185.85.241.68","last_name":"mahboob","last_sport_bet_time":1688544351,"loyalty_earned_points":0.0,"loyalty_exchanged_points":0.0,"loyalty_last_earned_points":0.0,"loyalty_level_id":2172,"loyalty_max_exchange_point":0,"loyalty_min_exchange_point":0,"loyalty_point":11853.0,"loyalty_point_usage_period":0,"mobile_phone":"989111376880","name":"Vahid Mahboob ","owner_id":null,"partner_client_category_id":315,"personal_id":null,"phone":"989358758276.wrong number","reg_date":"2017-09-24","site_id":934,"sport_bonus":10000.0,"sportsbook_profile_id":2,"status":null,"subscribe_to_bonus":true,"subscribe_to_email":true,"subscribe_to_internal_message":true,"subscribe_to_phone_call":true,"subscribe_to_push_notification":true,"subscribe_to_sms":true,"subscribed_to_news":false,"terms_and_conditions_acceptance_date":null,"terms_and_conditions_version":null,"unique_id":59581345,"unplayed_balance":0.67,"unread_count":0,"user_id":59581345,"username":"vahidmahboob60","zip_code":null}}'; // issue: phone

        // Failed responses
    case SessionNotFound = '{"code":5,"data":null,"msg":"Session not found"}';
    case RecaptchaVerificationNeeded = '{"code":27,"data":"6LfvKJMUAAAAAI0CmeiUEIurE3CFcCxwtf4SlUhk","msg":"recaptcha verification needed"}';
}
